"""rename care_circles to families

Revision ID: 048e3beb281c
Revises: 79ce57c057d0
Create Date: 2026-08-23 01:05:03.356942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '048e3beb281c'
down_revision: Union[str, None] = '79ce57c057d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_coordinator_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_coordinator_profile_id'], ['app_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_user')
    )
    # Drop dependent constraint from event_logs first
    op.drop_constraint('event_logs_care_circle_id_fkey', 'event_logs', type_='foreignkey')
    
    # Drop care_circle_members (which depends on care_circles)
    op.drop_table('care_circle_members')
    
    # Now safe to drop care_circles
    op.drop_table('care_circles')
    
    op.add_column('event_logs', sa.Column('family_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_event_logs_family_id', 'event_logs', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    op.drop_column('event_logs', 'care_circle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('care_circle_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_event_logs_family_id', 'event_logs', type_='foreignkey')

    op.create_foreign_key(op.f('event_logs_care_circle_id_fkey'), 'event_logs', 'care_circles', ['care_circle_id'], ['id'], ondelete='CASCADE')
    op.drop_column('event_logs', 'family_id')
    op.create_table('care_circle_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('care_circle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['care_circle_id'], ['care_circles.id'], name=op.f('care_circle_members_care_circle_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_profiles.id'], name=op.f('care_circle_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('care_circle_members_pkey')),
    sa.UniqueConstraint('care_circle_id', 'user_id', name=op.f('uq_care_circle_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('care_circles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('care_circles_pkey'))
    )
    op.drop_table('family_members')
    op.drop_table('families')
    # ### end Alembic commands ###
