"""add ai conversations table

Revision ID: 36ecbe1d56ab
Revises: f67af0587971
Create Date: 2026-08-23 06:59:01.652621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ecbe1d56ab'
down_revision: Union[str, None] = 'f67af0587971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('agent_session_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_type', sa.String(length=100), nullable=False),
    sa.Column('context_scope', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['app_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['care_subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'updated_at')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
