"""add appointment coordination table

Revision ID: a6b2af24a61c
Revises: 2a758309730f
Create Date: 2026-08-23 06:39:28.888171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b2af24a61c'
down_revision: Union[str, None] = '2a758309730f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_coordination',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('fhir_appointment_id', sa.String(length=255), nullable=False),
    sa.Column('assigned_caregiver_profile_id', sa.UUID(), nullable=True),
    sa.Column('preparation_status', sa.String(length=50), nullable=False),
    sa.Column('summary_status', sa.String(length=50), nullable=False),
    sa.Column('reminder_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_caregiver_profile_id'], ['app_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['care_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_coordination')
    # ### end Alembic commands ###
