"""update consents table schema

Revision ID: c43a3c328a5e
Revises: cb5555ff0b10
Create Date: 2026-08-23 01:20:58.057950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43a3c328a5e'
down_revision: Union[str, None] = 'cb5555ff0b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM consents")
    op.add_column('consents', sa.Column('family_id', sa.UUID(), nullable=False))
    op.add_column('consents', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.add_column('consents', sa.Column('grantor_profile_id', sa.UUID(), nullable=False))
    op.add_column('consents', sa.Column('grantee_profile_id', sa.UUID(), nullable=False))
    op.add_column('consents', sa.Column('consent_type', sa.String(length=50), nullable=False))
    op.add_column('consents', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('consents', sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('consents', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consents', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consents', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('consents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('consents', 'scope')
    op.add_column('consents', sa.Column('scope', sa.JSON(), nullable=False))
    # op.drop_constraint(op.f('uq_parent_grantee_scope'), 'consents', type_='unique')
    op.create_unique_constraint('uq_consent_flow', 'consents', ['family_id', 'subject_id', 'grantor_profile_id', 'grantee_profile_id'])
    op.execute("ALTER TABLE consents DROP CONSTRAINT IF EXISTS consents_grantee_id_fkey")
    op.execute("ALTER TABLE consents DROP CONSTRAINT IF EXISTS consents_parent_id_fkey")
    op.execute("ALTER TABLE consents DROP CONSTRAINT IF EXISTS fk_consents_grantee_id")
    op.execute("ALTER TABLE consents DROP CONSTRAINT IF EXISTS fk_consents_parent_id")
    op.create_foreign_key('fk_consents_grantee_profile_id', 'consents', 'app_profiles', ['grantee_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_consents_subject_id', 'consents', 'care_subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_consents_grantor_profile_id', 'consents', 'app_profiles', ['grantor_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_consents_family_id', 'consents', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    op.drop_column('consents', 'granted')
    op.drop_column('consents', 'grantee_id')
    op.drop_column('consents', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('consents', sa.Column('grantee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('consents', sa.Column('granted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_consents_grantee_profile_id', 'consents', type_='foreignkey')
    op.drop_constraint('fk_consents_subject_id', 'consents', type_='foreignkey')
    op.drop_constraint('fk_consents_grantor_profile_id', 'consents', type_='foreignkey')
    op.drop_constraint('fk_consents_family_id', 'consents', type_='foreignkey')

    op.create_foreign_key(op.f('consents_parent_id_fkey'), 'consents', 'app_profiles', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('consents_grantee_id_fkey'), 'consents', 'app_profiles', ['grantee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_consent_flow', 'consents', type_='unique')
    op.create_unique_constraint(op.f('uq_parent_grantee_scope'), 'consents', ['parent_id', 'grantee_id', 'scope'], postgresql_nulls_not_distinct=False)
    op.drop_column('consents', 'scope')
    op.add_column('consents', sa.Column('scope', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('consents', 'created_at')
    op.drop_column('consents', 'version')
    op.drop_column('consents', 'revoked_at')
    op.drop_column('consents', 'expires_at')
    op.drop_column('consents', 'granted_at')
    op.drop_column('consents', 'status')
    op.drop_column('consents', 'consent_type')
    op.drop_column('consents', 'grantee_profile_id')
    op.drop_column('consents', 'grantor_profile_id')
    op.drop_column('consents', 'subject_id')
    op.drop_column('consents', 'family_id')
    # ### end Alembic commands ###
