"""add ai_insight_sources table

Revision ID: e871663b0226
Revises: 8b236f8f3a4c
Create Date: 2026-08-23 01:37:08.542258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e871663b0226'
down_revision: Union[str, None] = '8b236f8f3a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insight_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['ai_insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_insight_sources')
    # ### end Alembic commands ###
