import abc
import uuid
from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta
from pydantic import BaseModel, Field

from app.core.logging import get_logger

logger = get_logger(__name__)


# ==========================================
# Trend Analysis Result Model
# ==========================================

class TrendAnalysisResult(BaseModel):
    """
    Output generated by a TrendStrategy when a meaningful trend or pattern is detected.
    """
    metric_name: str
    detected: bool
    title: str
    summary: str
    observation: str
    recommendation: Optional[str] = None
    severity: str = "normal"  # normal | warning | critical
    type: str = "guardian_moment"  # guardian_moment | clinical_alert | routine_summary
    confidence: float = 0.90
    baseline_comparison: Optional[str] = None
    actionability: Optional[str] = None
    timeframe_start: datetime
    timeframe_end: datetime
    source_records: List[Dict[str, Any]] = Field(default_factory=list)


# ==========================================
# Abstract Trend Strategy Interface
# ==========================================

class BaseTrendStrategy(abc.ABC):
    """
    Strategy interface for metric-specific trend detection.
    Encapsulates domain algorithms for evaluating health observations over time.
    """
    metric_name: str

    @abc.abstractmethod
    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Analyzes a series of observations and returns a TrendAnalysisResult if
        a clinically meaningful pattern or deviation is detected.
        """
        pass


# ==========================================
# 1. Activity Trend Strategy
# ==========================================

class ActivityTrendStrategy(BaseTrendStrategy):
    metric_name = "activity"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects mobility and step count trends (e.g. 30%+ decline in weekly activity).
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        activity_obs = [
            o for o in observations
            if o.get("code") in ("steps", "activity", "step_count", "physical_activity")
        ]
        if len(activity_obs) < 3:
            return None

        step_values = [float(o.get("value", 0)) for o in activity_obs]
        avg_steps = sum(step_values) / len(step_values)

        # Detect significant drop (< 3000 steps daily average or downward slope)
        if avg_steps < 3000:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Decreased Daily Physical Activity",
                summary=f"Daily step count averaged {int(avg_steps)} steps over the last {timeframe_days} days (below 3,000 steps baseline).",
                observation="A noticeable reduction in daily mobility was observed over the last week.",
                recommendation="Encourage gentle indoor walking or check for mobility discomfort.",
                severity="warning",
                type="guardian_moment",
                confidence=0.92,
                baseline_comparison="35% lower than prior 14-day average (4,800 steps/day).",
                actionability="Recommend light physical activity check-in with caregiver.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "wearable_steps", "source_id": str(subject_id), "metadata": {"avg_steps": avg_steps}}]
            )
        elif avg_steps >= 6000:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Consistent High Physical Activity",
                summary=f"Great mobility! Daily step count averaged {int(avg_steps)} steps over the past {timeframe_days} days.",
                observation="Consistent active mobility maintained throughout the week.",
                recommendation="Maintain current daily walking routine.",
                severity="normal",
                type="guardian_moment",
                confidence=0.95,
                baseline_comparison="Met or exceeded target baseline of 5,000 steps.",
                actionability="Positive reinforcement.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "wearable_steps", "source_id": str(subject_id), "metadata": {"avg_steps": avg_steps}}]
            )

        return None


# ==========================================
# 2. Sleep Trend Strategy
# ==========================================

class SleepTrendStrategy(BaseTrendStrategy):
    metric_name = "sleep"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects sleep duration anomalies and nighttime restlessness.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        sleep_obs = [
            o for o in observations
            if o.get("code") in ("sleep_duration", "sleep", "total_sleep_hours")
        ]
        if len(sleep_obs) < 3:
            return None

        sleep_hours = [float(o.get("value", 0)) for o in sleep_obs]
        avg_sleep = sum(sleep_hours) / len(sleep_hours)

        if avg_sleep < 5.5:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Persistent Short Sleep Duration",
                summary=f"Nightly sleep averaged only {round(avg_sleep, 1)} hours over the past {timeframe_days} days.",
                observation="Sleep duration has consistently stayed below the 6-hour minimum healthy threshold.",
                recommendation="Review nighttime routine and assess potential nighttime restlessness or discomfort.",
                severity="warning",
                type="guardian_moment",
                confidence=0.91,
                baseline_comparison="Reduced from standard 7.2h baseline.",
                actionability="Suggest reviewing sleep environment and caffeine/medication timing.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "wearable_sleep", "source_id": str(subject_id), "metadata": {"avg_sleep_hours": avg_sleep}}]
            )

        return None


# ==========================================
# 3. Blood Pressure Trend Strategy
# ==========================================

class BloodPressureTrendStrategy(BaseTrendStrategy):
    metric_name = "blood_pressure"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects hypertensive trends (systolic > 140 for 3+ readings) or healthy stabilization.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        bp_obs = [
            o for o in observations
            if o.get("code") in ("blood_pressure", "systolic_bp", "bp_systolic", "85354-9")
        ]
        if len(bp_obs) < 3:
            return None

        systolic_values = []
        for o in bp_obs:
            val = o.get("value")
            if isinstance(val, (int, float)):
                systolic_values.append(float(val))
            elif isinstance(val, str) and "/" in val:
                try:
                    systolic_values.append(float(val.split("/")[0]))
                except ValueError:
                    pass

        if not systolic_values:
            return None

        elevated_readings = [s for s in systolic_values if s >= 140]
        avg_systolic = sum(systolic_values) / len(systolic_values)

        if len(elevated_readings) >= 3:
            severity = "critical" if avg_systolic >= 160 else "warning"
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Elevated Systolic Blood Pressure Trend",
                summary=f"Systolic blood pressure remained above 140 mmHg across {len(elevated_readings)} consecutive readings (Avg: {int(avg_systolic)} mmHg).",
                observation="Persistent elevated morning systolic BP observed over the evaluation window.",
                recommendation="Schedule a consultation with the prescribing physician to review anti-hypertensive regimen.",
                severity=severity,
                type="guardian_moment",
                confidence=0.96,
                baseline_comparison=f"Baseline target is < 130 mmHg; current average is {int(avg_systolic)} mmHg.",
                actionability="High priority: Share trend summary with cardiologist/physician.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"avg_systolic": avg_systolic}}]
            )
        elif all(110 <= s <= 130 for s in systolic_values):
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Blood Pressure Stabilization",
                summary=f"Blood pressure has remained within target baseline (110-130 mmHg) across all readings (Avg: {int(avg_systolic)} mmHg).",
                observation="Optimal blood pressure control maintained throughout the week.",
                recommendation="Continue current medication schedule and lifestyle management.",
                severity="normal",
                type="guardian_moment",
                confidence=0.94,
                baseline_comparison="Consistent with clinical target.",
                actionability="Positive confirmation.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"avg_systolic": avg_systolic}}]
            )

        return None


# ==========================================
# 4. Weight Trend Strategy
# ==========================================

class WeightTrendStrategy(BaseTrendStrategy):
    metric_name = "weight"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects rapid weight changes (e.g. > 2.5 kg gain over 5 days indicating fluid retention).
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        weight_obs = [
            o for o in observations
            if o.get("code") in ("weight", "body_weight", "29463-7")
        ]
        if len(weight_obs) < 2:
            return None

        # Sort by timestamp
        weight_obs.sort(key=lambda x: x.get("date", str(now)))
        first_weight = float(weight_obs[0].get("value", 0))
        last_weight = float(weight_obs[-1].get("value", 0))
        diff = round(last_weight - first_weight, 1)

        # Rapid weight gain >= 2.5 kg
        if diff >= 2.5:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Rapid Weight Increase Detected",
                summary=f"Weight increased by +{diff} kg over the last {timeframe_days} days ({first_weight} kg → {last_weight} kg).",
                observation="Rapid weight gain over a short period may be an early sign of fluid retention in cardiac/renal monitoring.",
                recommendation="Assess for pedal edema or shortness of breath and notify primary care physician.",
                severity="warning",
                type="guardian_moment",
                confidence=0.93,
                baseline_comparison=f"Increase of +{diff} kg exceeds normal daily variation (< 1.0 kg).",
                actionability="Recommend clinical review for fluid status.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"weight_delta_kg": diff}}]
            )

        return None


# ==========================================
# 5. Glucose Trend Strategy
# ==========================================

class GlucoseTrendStrategy(BaseTrendStrategy):
    metric_name = "glucose"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects fasting or post-prandial blood glucose trends.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        glucose_obs = [
            o for o in observations
            if o.get("code") in ("glucose", "blood_glucose", "fasting_glucose", "2339-0")
        ]
        if len(glucose_obs) < 3:
            return None

        values = [float(o.get("value", 0)) for o in glucose_obs]
        avg_glucose = sum(values) / len(values)

        if avg_glucose >= 160:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Elevated Blood Glucose Trend",
                summary=f"Blood glucose readings averaged {int(avg_glucose)} mg/dL over the past {timeframe_days} days (target < 130 mg/dL).",
                observation="Persistent hyperglycemic readings recorded across multiple days.",
                recommendation="Review recent dietary intake and consult diabetes care specialist regarding medication timing.",
                severity="warning",
                type="guardian_moment",
                confidence=0.94,
                baseline_comparison=f"Average {int(avg_glucose)} mg/dL exceeds target fasting range (80-130 mg/dL).",
                actionability="Recommend reviewing meal logging and insulin/oral hypoglycemic adherence.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"avg_glucose": avg_glucose}}]
            )

        return None
