import abc
import uuid
from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta
from pydantic import BaseModel, Field

from app.core.logging import get_logger

logger = get_logger(__name__)


# ==========================================
# Trend Analysis Result Model
# ==========================================

class TrendAnalysisResult(BaseModel):
    """
    Output generated by a TrendStrategy when a meaningful trend or pattern is detected.
    """
    metric_name: str
    detected: bool
    title: str
    summary: str
    observation: str
    recommendation: Optional[str] = None
    severity: str = "normal"  # normal | warning | critical
    type: str = "guardian_moment"  # guardian_moment | clinical_alert | routine_summary
    confidence: float = 0.90
    baseline_comparison: Optional[str] = None
    actionability: Optional[str] = None
    actions: List[str] = Field(default_factory=list)  # Actionable options (e.g. Check in with Dad, Review trends)
    timeframe_start: datetime
    timeframe_end: datetime
    source_records: List[Dict[str, Any]] = Field(default_factory=list)


# ==========================================
# Abstract Trend Strategy Interface
# ==========================================

class BaseTrendStrategy(abc.ABC):
    """
    Strategy interface for metric-specific trend detection.
    Encapsulates domain algorithms for evaluating health observations over time.
    """
    metric_name: str

    @abc.abstractmethod
    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Analyzes a series of observations and returns a TrendAnalysisResult if
        a clinically meaningful pattern or deviation is detected.
        """
        pass


# ==========================================
# 1. Activity Trend Strategy
# ==========================================

class ActivityTrendStrategy(BaseTrendStrategy):
    metric_name = "activity"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects mobility and step count trends (e.g. 20%+ decline in activity).
        CLINICAL INVARIANT: Does NOT automatically interpret decreased activity as illness.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        activity_obs = [
            o for o in observations
            if o.get("code") in ("steps", "activity", "step_count", "physical_activity")
            and o.get("value") is not None
        ]
        if len(activity_obs) < 3:
            return None

        step_values = [float(o["value"]) for o in activity_obs]
        avg_steps = sum(step_values) / len(step_values)
        consecutive_days = len(activity_obs)

        # Baseline calculation: If historical baseline is present in observations or metadata, use it, else 6,210 standard baseline
        baseline_steps = 6210.0
        for o in observations:
            if "baseline" in o:
                try:
                    baseline_steps = float(o["baseline"])
                    break
                except Exception:
                    pass

        # Detect drop below baseline (e.g. average below 75% of baseline or < 5000)
        if avg_steps < (baseline_steps * 0.85):
            pct_below = int(round(((baseline_steps - avg_steps) / baseline_steps) * 100.0))
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title=f"Dad's activity has been below his usual level for {consecutive_days} days.",
                summary=(
                    f"Dad's activity has been below his usual level for {consecutive_days} days.\n\n"
                    f"Average:\n{int(round(avg_steps)):,} steps/day\n\n"
                    f"30-day baseline:\n{int(round(baseline_steps)):,} steps/day"
                ),
                observation=(
                    f"Observed daily average of {int(round(avg_steps)):,} steps/day is ~{pct_below}% below the 30-day baseline ({int(round(baseline_steps)):,} steps/day). "
                    f"Note: Decreased physical activity is a pattern deviation and should not be automatically interpreted as illness."
                ),
                recommendation="Reach out for a friendly check-in, review the multi-day activity trend, or contact the primary caregiver if needed.",
                actions=[
                    "Check in with Dad",
                    "Review trends",
                    "Contact caregiver"
                ],
                severity="warning" if pct_below >= 30 else "normal",
                type="guardian_moment",
                confidence=0.94,
                baseline_comparison=f"30-day baseline: {int(round(baseline_steps)):,} steps/day",
                actionability="propose_care_task",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "wearable_steps", "source_id": str(subject_id), "metadata": {"avg_steps": avg_steps, "baseline_steps": baseline_steps}}]
            )
        elif avg_steps >= 6000:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Consistent High Physical Activity",
                summary=f"Great mobility! Daily step count averaged {int(avg_steps):,} steps over the past {timeframe_days} days.",
                observation="Consistent active mobility maintained throughout the week.",
                recommendation="Maintain current daily walking routine.",
                actions=["Send encouragement", "Review trends"],
                severity="normal",
                type="guardian_moment",
                confidence=0.95,
                baseline_comparison=f"Met or exceeded target baseline of {int(baseline_steps):,} steps.",
                actionability="Positive reinforcement.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "wearable_steps", "source_id": str(subject_id), "metadata": {"avg_steps": avg_steps}}]
            )

        return None



# ==========================================
# 2. Sleep Trend Strategy
# ==========================================

class SleepTrendStrategy(BaseTrendStrategy):
    metric_name = "sleep"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects sleep duration anomalies and nighttime restlessness.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        sleep_obs = [
            o for o in observations
            if o.get("code") in ("sleep_duration", "sleep", "total_sleep_hours")
        ]
        if len(sleep_obs) < 3:
            return None

        sleep_hours = [float(o.get("value", 0)) for o in sleep_obs]
        avg_sleep = sum(sleep_hours) / len(sleep_hours)

        if avg_sleep < 5.5:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Persistent Short Sleep Duration",
                summary=f"Nightly sleep averaged only {round(avg_sleep, 1)} hours over the past {timeframe_days} days.",
                observation="Sleep duration has consistently stayed below the 6-hour minimum healthy threshold.",
                recommendation="Review nighttime routine and assess potential nighttime restlessness or discomfort.",
                severity="warning",
                type="guardian_moment",
                confidence=0.91,
                baseline_comparison="Reduced from standard 7.2h baseline.",
                actionability="Suggest reviewing sleep environment and caffeine/medication timing.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "wearable_sleep", "source_id": str(subject_id), "metadata": {"avg_sleep_hours": avg_sleep}}]
            )

        return None


# ==========================================
# 3. Blood Pressure Trend Strategy
# ==========================================

class BloodPressureTrendStrategy(BaseTrendStrategy):
    metric_name = "blood_pressure"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects hypertensive trends (systolic > 140 for 3+ readings) or healthy stabilization.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        bp_obs = [
            o for o in observations
            if o.get("code") in ("blood_pressure", "systolic_bp", "bp_systolic", "85354-9")
        ]
        if len(bp_obs) < 3:
            return None

        systolic_values = []
        for o in bp_obs:
            val = o.get("value")
            if isinstance(val, (int, float)):
                systolic_values.append(float(val))
            elif isinstance(val, str) and "/" in val:
                try:
                    systolic_values.append(float(val.split("/")[0]))
                except ValueError:
                    pass

        if not systolic_values:
            return None

        elevated_readings = [s for s in systolic_values if s >= 140]
        avg_systolic = sum(systolic_values) / len(systolic_values)

        if len(elevated_readings) >= 3:
            severity = "critical" if avg_systolic >= 160 else "warning"
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Elevated Systolic Blood Pressure Trend",
                summary=f"Systolic blood pressure remained above 140 mmHg across {len(elevated_readings)} consecutive readings (Avg: {int(avg_systolic)} mmHg).",
                observation="Persistent elevated morning systolic BP observed over the evaluation window.",
                recommendation="Schedule a consultation with the prescribing physician to review anti-hypertensive regimen.",
                severity=severity,
                type="guardian_moment",
                confidence=0.96,
                baseline_comparison=f"Baseline target is < 130 mmHg; current average is {int(avg_systolic)} mmHg.",
                actionability="High priority: Share trend summary with cardiologist/physician.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"avg_systolic": avg_systolic}}]
            )
        elif all(110 <= s <= 130 for s in systolic_values):
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Blood Pressure Stabilization",
                summary=f"Blood pressure has remained within target baseline (110-130 mmHg) across all readings (Avg: {int(avg_systolic)} mmHg).",
                observation="Optimal blood pressure control maintained throughout the week.",
                recommendation="Continue current medication schedule and lifestyle management.",
                severity="normal",
                type="guardian_moment",
                confidence=0.94,
                baseline_comparison="Consistent with clinical target.",
                actionability="Positive confirmation.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"avg_systolic": avg_systolic}}]
            )

        return None


# ==========================================
# 4. Weight Trend Strategy
# ==========================================

class WeightTrendStrategy(BaseTrendStrategy):
    metric_name = "weight"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects rapid weight changes (e.g. > 2.5 kg gain over 5 days indicating fluid retention).
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        weight_obs = [
            o for o in observations
            if o.get("code") in ("weight", "body_weight", "29463-7")
        ]
        if len(weight_obs) < 2:
            return None

        # Sort by timestamp
        weight_obs.sort(key=lambda x: x.get("date", str(now)))
        first_weight = float(weight_obs[0].get("value", 0))
        last_weight = float(weight_obs[-1].get("value", 0))
        diff = round(last_weight - first_weight, 1)

        # Rapid weight gain >= 2.5 kg
        if diff >= 2.5:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Rapid Weight Increase Detected",
                summary=f"Weight increased by +{diff} kg over the last {timeframe_days} days ({first_weight} kg → {last_weight} kg).",
                observation="Rapid weight gain over a short period may be an early sign of fluid retention in cardiac/renal monitoring.",
                recommendation="Assess for pedal edema or shortness of breath and notify primary care physician.",
                severity="warning",
                type="guardian_moment",
                confidence=0.93,
                baseline_comparison=f"Increase of +{diff} kg exceeds normal daily variation (< 1.0 kg).",
                actionability="Recommend clinical review for fluid status.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"weight_delta_kg": diff}}]
            )

        return None


# ==========================================
# 5. Glucose Trend Strategy
# ==========================================

class GlucoseTrendStrategy(BaseTrendStrategy):
    metric_name = "glucose"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects fasting or post-prandial blood glucose trends.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        glucose_obs = [
            o for o in observations
            if o.get("code") in ("glucose", "blood_glucose", "fasting_glucose", "2339-0")
        ]
        if len(glucose_obs) < 3:
            return None

        values = [float(o.get("value", 0)) for o in glucose_obs]
        avg_glucose = sum(values) / len(values)

        if avg_glucose >= 160:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Elevated Blood Glucose Trend",
                summary=f"Blood glucose readings averaged {int(avg_glucose)} mg/dL over the past {timeframe_days} days (target < 130 mg/dL).",
                observation="Persistent hyperglycemic readings recorded across multiple days.",
                recommendation="Review recent dietary intake and consult diabetes care specialist regarding medication timing.",
                severity="warning",
                type="guardian_moment",
                confidence=0.94,
                baseline_comparison=f"Average {int(avg_glucose)} mg/dL exceeds target fasting range (80-130 mg/dL).",
                actionability="Recommend reviewing meal logging and insulin/oral hypoglycemic adherence.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "fhir_observation", "source_id": str(subject_id), "metadata": {"avg_glucose": avg_glucose}}]
            )

        return None


# ==========================================
# 6. Wearable Cardiovascular & Recovery Trend Strategy
# ==========================================

class WearableCardiovascularTrendStrategy(BaseTrendStrategy):
    metric_name = "cardiovascular_recovery"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Detects resting heart rate elevation or severe HRV depression from wearable telemetry.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        hr_obs = [
            o for o in observations
            if o.get("code") in ("resting_heart_rate", "heart_rate", "rhr", "40443-4", "8867-4")
            and o.get("value") is not None
        ]
        if len(hr_obs) < 3:
            return None

        hr_values = [float(o["value"]) for o in hr_obs if o.get("value") is not None]
        avg_rhr = sum(hr_values) / len(hr_values)

        # Baseline resting heart rate is typically 65-70 bpm. If rolling avg > 78 bpm:
        if avg_rhr >= 78.0:
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title="Elevated Resting Heart Rate Trend",
                summary=f"Resting heart rate averaged {int(avg_rhr)} bpm over the past {timeframe_days} days (elevated vs 68 bpm baseline).",
                observation="Autonomic recovery vitals indicate sustained cardiovascular exertion or physiological stress.",
                recommendation="Monitor hydration, ensure adequate sleep, and consider checking for infection or medication adjustments.",
                severity="warning",
                type="guardian_moment",
                confidence=0.93,
                baseline_comparison=f"Rolling average of {int(avg_rhr)} bpm exceeds normal baseline (65-70 bpm).",
                actionability="Recommend assessing vital signs and checking in on daily stress levels.",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "wearable_recovery", "source_id": str(subject_id), "metadata": {"avg_rhr": avg_rhr}}]
            )

        return None



# ==========================================
# 7. Multi-Source Health Correlation Strategy
# ==========================================

from app.domains.insights.correlation import (
    MultiSourceHealthContext,
    MultiSourceCorrelationEngine,
    MultiSourceCorrelationResult
)


class MultiSourceCorrelationStrategy(BaseTrendStrategy):
    metric_name = "multi_source_correlation"

    async def analyze(
        self,
        subject_id: uuid.UUID,
        family_id: uuid.UUID,
        observations: List[Dict[str, Any]],
        timeframe_days: int = 7
    ) -> Optional[TrendAnalysisResult]:
        """
        Correlates wearable metrics (activity, sleep, vitals) with medication adherence,
        care-subject check-ins, appointments, reported symptoms, and caregiver reports.
        """
        now = datetime.now()
        start = now - timedelta(days=timeframe_days)

        # 1. Parse Wearable Activity
        steps_obs = [o for o in observations if o.get("code") in ("steps", "activity", "step_count") and o.get("value") is not None]
        avg_steps = sum(float(o["value"]) for o in steps_obs) / len(steps_obs) if steps_obs else None
        baseline_steps = 6210.0

        # 2. Parse Wearable Sleep
        sleep_obs = [o for o in observations if o.get("code") in ("sleep_duration", "sleep", "total_sleep_hours") and o.get("value") is not None]
        # In hours
        sleep_vals = []
        for o in sleep_obs:
            v = float(o["value"])
            if v > 24.0:  # In minutes
                sleep_vals.append(v / 60.0)
            else:
                sleep_vals.append(v)
        avg_sleep_hrs = sum(sleep_vals) / len(sleep_vals) if sleep_vals else None
        baseline_sleep_hrs = 7.0

        # 3. Parse Medication Adherence
        med_obs = [o for o in observations if o.get("code") in ("medication", "medication_adherence", "adherence")]
        med_status = "normal"
        if med_obs:
            med_status = str(med_obs[-1].get("status") or med_obs[-1].get("value") or "normal")

        # 4. Parse Check-in
        checkin_obs = [o for o in observations if o.get("code") in ("checkin", "check_in", "parent_checkin", "mood")]
        latest_checkin = None
        if checkin_obs:
            latest_checkin = str(checkin_obs[-1].get("value") or checkin_obs[-1].get("response") or "Okay")

        # 5. Parse Symptoms
        symptom_obs = [o for o in observations if o.get("code") in ("symptom", "symptoms")]
        symptoms = [str(s.get("value")) for s in symptom_obs if s.get("value")]

        # Determine activity & sleep trends
        act_trend = "normal"
        if avg_steps is not None:
            if avg_steps < (baseline_steps * 0.8):
                act_trend = "below"
            elif avg_steps > (baseline_steps * 1.2):
                act_trend = "above"

        slp_trend = "normal"
        if avg_sleep_hrs is not None:
            if avg_sleep_hrs < (baseline_sleep_hrs * 0.8):
                slp_trend = "below"

        # Build Holistic Context
        ctx = MultiSourceHealthContext(
            subject_id=subject_id,
            family_id=family_id,
            subject_name="Dad",
            activity_steps_today=int(avg_steps) if avg_steps else None,
            activity_baseline_steps=int(baseline_steps),
            activity_trend=act_trend,
            sleep_hours_today=round(avg_sleep_hrs, 1) if avg_sleep_hrs else None,
            sleep_baseline_hours=baseline_sleep_hrs,
            sleep_trend=slp_trend,
            medication_adherence_status=med_status,
            latest_checkin_status=latest_checkin,
            reported_symptoms=symptoms
        )

        corr_res: MultiSourceCorrelationResult = MultiSourceCorrelationEngine.correlate(ctx)

        # If a non-trivial correlation is detected (e.g. severity attention or warning)
        if corr_res.severity in ("attention", "warning") or (act_trend == "below" and slp_trend == "below"):
            return TrendAnalysisResult(
                metric_name=self.metric_name,
                detected=True,
                title=corr_res.title,
                summary=corr_res.narrative_summary,
                observation=corr_res.observation,
                recommendation=corr_res.recommendation,
                actions=corr_res.actions,
                severity=corr_res.severity,
                type=corr_res.type,
                confidence=corr_res.confidence,
                baseline_comparison=f"Activity ({int(avg_steps or 0):,} vs {int(baseline_steps):,} steps), Sleep ({avg_sleep_hrs or 0:.1f} vs {baseline_sleep_hrs} hrs)",
                actionability="propose_care_task",
                timeframe_start=start,
                timeframe_end=now,
                source_records=[{"source_type": "multi_source_correlation", "source_id": str(subject_id), "metadata": corr_res.signals}]
            )

        return None


