"""add aggregate and actor columns to event logs table

Revision ID: 3d3b244b7242
Revises: b2f944317df8
Create Date: 2026-08-23 07:04:38.681638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3b244b7242'
down_revision: Union[str, None] = 'b2f944317df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('aggregate_type', sa.String(length=100), nullable=True))
    op.add_column('event_logs', sa.Column('aggregate_id', sa.String(length=255), nullable=True))
    op.add_column('event_logs', sa.Column('actor_profile_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_event_logs_actor_profile_id', 'event_logs', 'app_profiles', ['actor_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_event_logs_actor_profile_id', 'event_logs', type_='foreignkey')
    op.drop_column('event_logs', 'actor_profile_id')
    op.drop_column('event_logs', 'aggregate_id')
    op.drop_column('event_logs', 'aggregate_type')
    # ### end Alembic commands ###

