"""rename users to app_profiles

Revision ID: 79ce57c057d0
Revises: 0a475dddcfdc
Create Date: 2026-08-23 01:02:44.062632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79ce57c057d0'
down_revision: Union[str, None] = '0a475dddcfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iam_subject_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('avatar_file_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_profiles_email'), 'app_profiles', ['email'], unique=False)
    op.create_index(op.f('ix_app_profiles_iam_subject_id'), 'app_profiles', ['iam_subject_id'], unique=True)
    
    # Drop constraints first to avoid DependentObjectsStillExistError
    op.drop_constraint('care_circle_members_user_id_fkey', 'care_circle_members', type_='foreignkey')
    op.drop_constraint('consents_grantee_id_fkey', 'consents', type_='foreignkey')
    op.drop_constraint('consents_parent_id_fkey', 'consents', type_='foreignkey')
    
    # Drop old index and table
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    
    # Create new foreign keys pointing to app_profiles
    op.create_foreign_key('fk_care_circle_members_user_id', 'care_circle_members', 'app_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_consents_parent_id', 'consents', 'app_profiles', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_consents_grantee_id', 'consents', 'app_profiles', ['grantee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event_logs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_logs', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('fk_consents_parent_id', 'consents', type_='foreignkey')
    op.drop_constraint('fk_consents_grantee_id', 'consents', type_='foreignkey')
    op.create_foreign_key(op.f('consents_parent_id_fkey'), 'consents', 'users', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('consents_grantee_id_fkey'), 'consents', 'users', ['grantee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_care_circle_members_user_id', 'care_circle_members', type_='foreignkey')
    op.create_foreign_key(op.f('care_circle_members_user_id_fkey'), 'care_circle_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_app_profiles_iam_subject_id'), table_name='app_profiles')
    op.drop_index(op.f('ix_app_profiles_email'), table_name='app_profiles')
    op.drop_table('app_profiles')
    # ### end Alembic commands ###
