"""add guardian moments columns

Revision ID: 8ef5c299e5f6
Revises: e871663b0226
Create Date: 2026-08-23 01:39:28.178120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef5c299e5f6'
down_revision: Union[str, None] = 'e871663b0226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_insights', sa.Column('trigger_type', sa.String(length=100), nullable=True))
    op.add_column('ai_insights', sa.Column('baseline_comparison', sa.String(), nullable=True))
    op.add_column('ai_insights', sa.Column('actionability', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_insights', 'actionability')
    op.drop_column('ai_insights', 'baseline_comparison')
    op.drop_column('ai_insights', 'trigger_type')
    # ### end Alembic commands ###
