"""add document extractions table

Revision ID: f67af0587971
Revises: 131fcc63d2b3
Create Date: 2026-08-23 06:54:12.699334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67af0587971'
down_revision: Union[str, None] = '131fcc63d2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_type', sa.String(length=100), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('normalized_output', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by_profile_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['health_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_profile_id'], ['app_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_extractions')
    # ### end Alembic commands ###
